apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-app:latest  # Usamos esta etiqueta al construir localmente
          imagePullPolicy: Never      # IMPORTANTE para usar imágenes locales en Minikube
          ports:
            - containerPort: 8000
          env:
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: SECRET_KEY
              value: "supersecretkey"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/db-postgres"
